<?php

namespace Database\Seeders;

use App\Models\Award;
use Illuminate\Database\Seeder;

class AwardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $awards = [
            [
                'display_order' => 1,
                'name' => 'Parliamentary Medal of Valor',
                'code' => 'PMV',
                'post_nominal' => 'PMV',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 5,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4567',
            ],
            [
                'display_order' => 2,
                'name' => 'Queen\'s Cross of Bravery',
                'code' => 'QCB',
                'post_nominal' => 'QCB',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 4,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4568',
            ],
            [
                'display_order' => 3,
                'name' => 'Adrienne Cross',
                'code' => 'AC',
                'post_nominal' => 'AC',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2018-05-28 18:35:30',
                'points' => 4,
                'star_nation' => 'manticore',
                'id' => '5b0c4bf2cbe77603d215d955',
            ],
            [
                'display_order' => 4,
                'name' => 'Most Noble Order of the Star Kingdom',
                'code' => 'KSK',
                'post_nominal' => 'KSK',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 4,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4569',
            ],
            [
                'display_order' => 5,
                'name' => 'Knight Grand Cross of the Most Honorable Order of King Roger',
                'code' => 'GCR',
                'post_nominal' => 'GCR',
                'replaces' => 'KDR,KCR,KR,CR,OR,MR,RM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Honorable Order of King Roger',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 4,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b456a',
            ],
            [
                'display_order' => 6,
                'name' => 'Knight Grand Cross of the Most Eminent Order of the Golden Lion',
                'code' => 'GCGL',
                'post_nominal' => 'GCGL',
                'replaces' => 'KDGL,KCGL,KGL,CGL,OGL,MGL,GLM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Eminent Order of the Golden Lion',
                'updated_at' => '2019-04-09 01:28:48',
                'created_at' => '2018-05-28 18:35:30',
                'points' => 4,
                'star_nation' => 'manticore',
                'id' => '5b0c4bf2cbe77603d215d956',
            ],
            [
                'display_order' => 7,
                'name' => 'Knight Grand Cross of the Most Regal Order of Queen Elizabeth',
                'code' => 'GCE',
                'post_nominal' => 'GCE',
                'replaces' => 'KDE,KCE,KE,CE,OE,ME,EM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Regal Order of Queen Elizabeth',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 4,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b456b',
            ],
            [
                'display_order' => 8,
                'name' => 'Most Distinguished Order of Merit',
                'code' => 'OM',
                'post_nominal' => 'OM',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 3,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b456c',
            ],
            [
                'display_order' => 9,
                'name' => 'Knight Commander of the Most Honorable Order of King Roger',
                'code' => 'KDR',
                'post_nominal' => 'KDR',
                'replaces' => 'KCR,KR,CR,OR,MR,RM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Honorable Order of King Roger',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 3.5,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b456d',
            ],
            [
                'display_order' => 10,
                'name' => 'Knight Commander of the Most Eminent Order of the Golden Lion',
                'code' => 'KDGL',
                'post_nominal' => 'KDGL',
                'replaces' => 'GCGL,KCGL,KGL,CGL,OGL,MGL,GLM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Eminent Order of the Golden Lion',
                'updated_at' => '2019-04-09 01:28:48',
                'created_at' => '2018-05-28 18:35:30',
                'points' => 3.5,
                'star_nation' => 'manticore',
                'id' => '5b0c4bf2cbe77603d215d957',
            ],
            [
                'display_order' => 11,
                'name' => 'Knight Commander of the Most Regal Order of Queen Elizabeth',
                'code' => 'KDE',
                'post_nominal' => 'KDE',
                'replaces' => 'KCE,KE,CE,OE,ME,EM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Regal Order of Queen Elizabeth',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 3.5,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b456e',
            ],
            [
                'display_order' => 12,
                'name' => 'Knight Companion of the Most Honorable Order of King Roger',
                'code' => 'KCR',
                'post_nominal' => 'KCR',
                'replaces' => 'KR,CR,OR,MR,RM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Honorable Order of King Roger',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 3,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b456f',
            ],
            [
                'display_order' => 13,
                'name' => 'Knight Companion of the Most Eminent Order of the Golden Lion',
                'code' => 'KCGL',
                'post_nominal' => 'KCGL',
                'replaces' => 'GCGL,KDGL,KGL,CGL,OGL,MGL,GLM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Eminent Order of the Golden Lion',
                'updated_at' => '2019-04-09 01:28:48',
                'created_at' => '2018-05-28 18:35:30',
                'points' => 3,
                'star_nation' => 'manticore',
                'id' => '5b0c4bf2cbe77603d215d958',
            ],
            [
                'display_order' => 14,
                'name' => 'Knight Companion of the Most Regal Order of Queen Elizabeth',
                'code' => 'KCE',
                'post_nominal' => 'KCE',
                'replaces' => 'KE,CE,OE,ME,EM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Regal Order of Queen Elizabeth',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 3,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4570',
            ],
            [
                'display_order' => 15,
                'name' => 'Manticore Cross',
                'code' => 'MC',
                'post_nominal' => 'MC',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4571',
            ],
            [
                'display_order' => 16,
                'name' => 'Osterman Cross',
                'code' => 'OC',
                'post_nominal' => 'OC',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4572',
            ],
            [
                'display_order' => 18,
                'name' => 'Knight of the Most Honorable Order of King Roger',
                'code' => 'KR',
                'post_nominal' => 'KR',
                'replaces' => 'CR,OR,MR,RM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Honorable Order of King Roger',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2.5,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4573',
            ],
            [
                'display_order' => 19,
                'name' => 'Knight of the Most Eminent Order of the Golden Lion',
                'code' => 'KGL',
                'post_nominal' => 'KGL',
                'replaces' => 'GCGL,KDGL,KCGL,CGL,OGL,MGL,GLM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Eminent Order of the Golden Lion',
                'star_nation' => 'manticore',
                'points' => 2.5,
                'updated_at' => '2019-04-09 01:28:48',
                'created_at' => '2019-04-09 01:28:48',
                'id' => '5cabf5509c6b7f72b65084b2',
            ],
            [
                'display_order' => 20,
                'name' => 'Knight of the Most Regal Order of Queen Elizabeth',
                'code' => 'KE',
                'post_nominal' => 'KE',
                'replaces' => 'CE,OE,ME,EM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Regal Order of Queen Elizabeth',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2.5,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4574',
            ],
            [
                'display_order' => 21,
                'name' => 'Companion of the Most Honorable Order of King Roger',
                'code' => 'CR',
                'post_nominal' => 'CR',
                'replaces' => 'OR,MR,RM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Honorable Order of King Roger',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4575',
            ],
            [
                'display_order' => 22,
                'name' => 'Companion of the Most Eminent Order of the Golden Lion',
                'code' => 'CGL',
                'post_nominal' => 'CGL',
                'replaces' => 'GCGL,KDGL,KCGL,KGL,OGL,MGL,GLM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Eminent Order of the Golden Lion',
                'updated_at' => '2019-04-09 01:28:48',
                'created_at' => '2018-05-28 18:35:30',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5b0c4bf2cbe77603d215d959',
            ],
            [
                'display_order' => 23,
                'name' => 'Companion of the Most Regal Order of Queen Elizabeth',
                'code' => 'CE',
                'post_nominal' => 'CE',
                'replaces' => 'OE,ME,EM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Regal Order of Queen Elizabeth',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4576',
            ],
            [
                'display_order' => 24,
                'name' => 'Saganami Cross',
                'code' => 'SC',
                'post_nominal' => 'SC',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4577',
            ],
            [
                'display_order' => 26,
                'name' => 'Distinguished Gallantry Cross',
                'code' => 'DGC',
                'post_nominal' => 'DGC',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4578',
            ],
            [
                'display_order' => 27,
                'name' => 'Officer of the Most Honorable Order of King Roger',
                'code' => 'OR',
                'post_nominal' => 'OR',
                'replaces' => 'MR,RM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Honorable Order of King Roger',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1.5,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4579',
            ],
            [
                'display_order' => 28,
                'name' => 'Officer of the Most Eminent Order of the Golden Lion',
                'code' => 'OGL',
                'post_nominal' => 'OGL',
                'replaces' => 'GCGL,KDGL,KCGL,KGL,CGL,MGL,GLM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Eminent Order of the Golden Lion',
                'updated_at' => '2019-04-09 01:28:48',
                'created_at' => '2018-05-28 18:35:30',
                'points' => 1.5,
                'star_nation' => 'manticore',
                'id' => '5b0c4bf2cbe77603d215d95a',
            ],
            [
                'display_order' => 29,
                'name' => 'Officer of the Order of Queen Elizabeth',
                'code' => 'OE',
                'post_nominal' => 'OE',
                'replaces' => 'ME,EM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Regal Order of Queen Elizabeth',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1.5,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b457a',
            ],
            [
                'display_order' => 30,
                'name' => 'Order of Gallantry',
                'code' => 'OG',
                'post_nominal' => 'OG',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b457b',
            ],
            [
                'display_order' => 31,
                'name' => 'Navy Star',
                'code' => 'NS',
                'post_nominal' => 'NS',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b457c',
            ],
            [
                'display_order' => 32,
                'name' => 'Distinguished Service Order',
                'code' => 'DSO',
                'post_nominal' => 'DSO',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b457d',
            ],
            [
                'display_order' => 33,
                'name' => 'Member of the Most Honorable Order of King Roger',
                'code' => 'MR',
                'post_nominal' => 'MR',
                'replaces' => 'RM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Honorable Order of King Roger',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b457e',
            ],
            [
                'display_order' => 34,
                'name' => 'Member of the Most Eminent Order of the Golden Lion',
                'code' => 'MGL',
                'post_nominal' => 'MGL',
                'replaces' => 'GCGL,KDGL,KCGL,KGL,CGL,OGL,GLM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Eminent Order of the Golden Lion',
                'updated_at' => '2019-04-09 01:28:48',
                'created_at' => '2018-05-28 18:35:30',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5b0c4bf2cbe77603d215d95b',
            ],
            [
                'display_order' => 37,
                'name' => 'Member of the Most Regal Order of Queen Elizabeth',
                'code' => 'ME',
                'post_nominal' => 'ME',
                'replaces' => 'EM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Regal Order of Queen Elizabeth',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b457f',
            ],
            [
                'display_order' => 41,
                'name' => 'Conspicuous Gallantry Medal',
                'code' => 'CGM',
                'post_nominal' => 'CGM',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4581',
            ],
            [
                'display_order' => 42,
                'name' => 'Gryphon Star',
                'code' => 'GS',
                'post_nominal' => 'GS',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4582',
            ],
            [
                'display_order' => 43,
                'name' => 'Order of the Crown for Naval Service',
                'code' => 'OCN',
                'post_nominal' => 'OCN',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4583',
            ],
            [
                'display_order' => 47,
                'name' => 'Queen\'s Bravery Medal',
                'code' => 'QBM',
                'post_nominal' => 'QBM',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4585',
            ],
            [
                'display_order' => 48,
                'name' => 'Sphinx Cross',
                'code' => 'SphC',
                'post_nominal' => 'SXC',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2025-06-29 17:17:01',
                'created_at' => '2016-11-13 22:16:46',
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4586',
            ],
            [
                'display_order' => 49,
                'name' => 'Royal Household Distinguished Service Medal',
                'code' => 'RHDSM',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4587',
            ],
            [
                'display_order' => 53,
                'name' => 'Medal,Most Honorable Order of King Roger',
                'code' => 'RM',
                'post_nominal' => 'RM',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Honorable Order of King Roger',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 0.5,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4589',
            ],
            [
                'display_order' => 54,
                'name' => 'Medal, Most Eminent Order of the Golden Lion',
                'code' => 'GLM',
                'post_nominal' => 'GLM',
                'replaces' => 'GCGL,KDGL,KCGL,KGL,CGL,OGL,MGL',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Eminent Order of the Golden Lion',
                'updated_at' => '2019-04-09 01:28:48',
                'created_at' => '2018-05-28 18:35:30',
                'points' => 0.5,
                'star_nation' => 'manticore',
                'id' => '5b0c4bf2cbe77603d215d95c',
            ],
            [
                'display_order' => 55,
                'name' => 'Medal,Most Regal Order of Queen Elizabeth',
                'code' => 'EM',
                'post_nominal' => 'EM',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Most Regal Order of Queen Elizabeth',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 0.5,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b458a',
            ],
            [
                'display_order' => 56,
                'name' => 'Conspicuous Bravery Medal',
                'code' => 'CBM',
                'post_nominal' => 'CBM',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b458b',
            ],
            [
                'display_order' => 57,
                'name' => 'Conspicuous Service Medal',
                'code' => 'CSM',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b458c',
            ],
            [
                'display_order' => 58,
                'name' => 'Meritorious Service Medal',
                'code' => 'MSM',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b458d',
            ],
            [
                'display_order' => 59,
                'name' => 'Navy Commendation Decoration',
                'code' => 'NCD',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b458e',
            ],
            [
                'display_order' => 60,
                'name' => 'Navy/Marine Achievement Medal',
                'code' => 'NMAM',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b458f',
            ],
            [
                'display_order' => 61,
                'name' => 'List of Honor Citation (Chapter)',
                'code' => 'LOH',
                'post_nominal' => '',
                'replaces' => 'LOHP',
                'location' => 'R',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'group_label' => 'List of Honor Citation',
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4590',
            ],
            [
                'display_order' => 61,
                'name' => 'List of Honor Citation (Personal)',
                'code' => 'LOHP',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'R',
                'multiple' => false,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'id' => '5b0c4bf2cbe77603d215d969',
            ],
            [
                'display_order' => 62,
                'name' => 'Royal Unit Citation for Gallantry',
                'code' => 'RUCG',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'R',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4591',
            ],
            [
                'display_order' => 63,
                'name' => 'Royal Meritorious Unit Citation',
                'code' => 'RMUC',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'R',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4592',
            ],
            [
                'display_order' => 64,
                'name' => 'Fleet Excellence Award in Silver',
                'code' => 'FEAS',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'id' => '5b0c4bf2cbe77603d215d990',
            ],
            [
                'display_order' => 65,
                'name' => 'Fleet Excellence Award in Gold',
                'code' => 'FEA',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4593',
            ],
            [
                'display_order' => 66,
                'name' => 'Prisoner Of War Medal',
                'code' => 'POW',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4594',
            ],
            [
                'display_order' => 67,
                'name' => 'Survivor\'s Cross',
                'code' => 'SvC',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4595',
            ],
            [
                'display_order' => 68,
                'name' => 'Silesian Anti-Piracy Campaign Medal',
                'code' => 'SAPC',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4596',
            ],
            [
                'display_order' => 69,
                'name' => 'Masadan Occupation Medal',
                'code' => 'MOM',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4597',
            ],
            [
                'display_order' => 70,
                'name' => 'Havenite War Campaign Medal',
                'code' => 'HWC',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4598',
            ],
            [
                'display_order' => 71,
                'name' => 'Havenite Operation Service Medal',
                'code' => 'HOSM',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b4599',
            ],
            [
                'display_order' => 72,
                'name' => 'Manticore-Havenite 1905-1922 War Medal',
                'code' => 'MHW',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b459a',
            ],
            [
                'display_order' => 73,
                'name' => 'Grand Alliance Campaign Medal',
                'code' => 'GACM',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b459b',
            ],
            [
                'display_order' => 74,
                'name' => 'Yawata Strike Memorial Ribbon',
                'code' => 'YSMR',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'star_nation' => 'manticore',
                'updated_at' => '2024-02-20 02:51:42',
                'created_at' => '2024-02-20 02:51:42',
                'id' => '65d413be9c6b7f07f0024c92',
            ],
            [
                'display_order' => 75,
                'name' => 'King Roger III Coronation Medal',
                'code' => 'KR3CM',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'updated_at' => '2024-02-20 02:51:42',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b459c',
            ],
            [
                'display_order' => 76,
                'name' => 'Queen Elizabeth III Coronation Medal',
                'code' => 'QE3CM',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'updated_at' => '2024-02-20 02:51:42',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b459d',
            ],
            [
                'display_order' => 77,
                'name' => 'Queen Elizabeth III Silver Jubilee Medal',
                'code' => 'QE3SJM',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'updated_at' => '2024-02-20 02:51:42',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 1,
                'id' => '5b0c4bf2cbe77603d215d96a',
            ],
            [
                'display_order' => 78,
                'name' => 'Queen Elizabeth III Gold Jubilee Medal',
                'code' => 'QE3GJM',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'updated_at' => '2024-02-20 02:51:42',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'id' => '5b0c4bf2cbe77603d215d96b',
            ],
            [
                'display_order' => 79,
                'name' => 'Manticoran Combat Action Medal',
                'code' => 'MCAM',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => true,
                'updated_at' => '2024-02-20 02:51:42',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b459e',
            ],
            [
                'display_order' => 80,
                'name' => 'Manticoran Service Medal',
                'code' => 'MtSM',
                'post_nominal' => '',
                'replaces' => 'MRSM,GCM',
                'location' => 'L',
                'multiple' => true,
                'group_label' => 'Length of Service Awards',
                'updated_at' => '2024-02-20 02:51:42',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b459f',
            ],
            [
                'display_order' => 81,
                'name' => 'Manticoran Reserve Service Medal',
                'code' => 'MRSM',
                'post_nominal' => '',
                'replaces' => 'MtSM,GCM',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Length of Service Awards',
                'updated_at' => '2024-02-20 02:51:42',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45a0',
            ],
            [
                'display_order' => 82,
                'name' => 'Good Conduct Medal',
                'code' => 'GCM',
                'post_nominal' => '',
                'replaces' => 'MtSM,MRSM',
                'location' => 'L',
                'multiple' => true,
                'group_label' => 'Length of Service Awards',
                'updated_at' => '2024-02-20 02:51:42',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45a1',
            ],
            [
                'display_order' => 83,
                'name' => 'Space Service Deployment Ribbon',
                'code' => 'SSD',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'updated_at' => '2024-02-20 02:51:42',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45a2',
            ],
            [
                'display_order' => 84,
                'name' => 'Navy Rifle High Expert Ribbon',
                'code' => 'NRHE',
                'post_nominal' => '',
                'replaces' => 'NRE,NRS,NRMC',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Rifle Marksmanship',
                'updated_at' => '2024-02-20 02:51:42',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 4,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45a3',
            ],
            [
                'display_order' => 85,
                'name' => 'Navy Pistol High Expert Ribbon',
                'code' => 'NPHE',
                'post_nominal' => '',
                'replaces' => 'NPE,NPS,NPMC',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Pistol Marksmanship',
                'updated_at' => '2024-02-20 02:51:42',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 4,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45a4',
            ],
            [
                'display_order' => 94,
                'name' => 'Navy Rifle Expert Ribbon',
                'code' => 'NRE',
                'post_nominal' => '',
                'replaces' => 'NRS,NRMC',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Rifle Marksmanship',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 3,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45a5',
            ],
            [
                'display_order' => 95,
                'name' => 'Navy Pistol Expert Ribbon',
                'code' => 'NPE',
                'post_nominal' => '',
                'replaces' => 'NPS,NPMC',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Pistol Marksmanship',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 3,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45a6',
            ],
            [
                'display_order' => 105,
                'name' => 'Navy Rifle Sharpshooter Ribbon',
                'code' => 'NRS',
                'post_nominal' => '',
                'replaces' => ',NRMC',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Rifle Marksmanship',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45a7',
            ],
            [
                'display_order' => 106,
                'name' => 'Navy Pistol Sharpshooter Ribbon',
                'code' => 'NPS',
                'post_nominal' => '',
                'replaces' => ',NPMC',
                'location' => 'L',
                'multiple' => false,
                'group_label' => 'Pistol Marksmanship',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 2,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45a8',
            ],
            [
                'display_order' => 116,
                'name' => 'Navy Rifle Marksmanship Certificate',
                'code' => 'NRMC',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'NA',
                'multiple' => false,
                'group_label' => 'Rifle Marksmanship',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2018-05-28 18:35:30',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5b0c4bf2cbe77603d215d95d',
            ],
            [
                'display_order' => 117,
                'name' => 'Navy Pistol Marksmanship Certificate',
                'code' => 'NPMC',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'NA',
                'multiple' => false,
                'group_label' => 'Pistol Marksmanship',
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2018-05-28 18:35:30',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5b0c4bf2cbe77603d215d95e',
            ],
            [
                'display_order' => 127,
                'name' => 'Recruit Training Ribbon',
                'code' => 'RTR',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45a9',
            ],
            [
                'display_order' => 128,
                'name' => 'NCO Senior Course Ribbon',
                'code' => 'NCOSCR',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45aa',
            ],
            [
                'display_order' => 129,
                'name' => 'Armed Forces Service Medal',
                'code' => 'AFSM',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'L',
                'multiple' => false,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2016-11-13 22:16:46',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45ab',
            ],
            [
                'display_order' => 1000,
                'name' => 'Command Hyperstar',
                'code' => 'HS',
                'post_nominal' => '',
                'replaces' => 'OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => true,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2016-11-13 22:16:46',
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45ac',
            ],
            [
                'display_order' => 1001,
                'name' => 'Officer Space Warfare Pin',
                'code' => 'OSWP',
                'post_nominal' => '',
                'replaces' => 'ESWP,HS,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2016-11-13 22:16:46',
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45ad',
            ],
            [
                'display_order' => 1002,
                'name' => 'Enlisted Space Warfare Pin',
                'code' => 'ESWP',
                'post_nominal' => '',
                'replaces' => 'OSWP,HS,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => true,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2016-11-13 22:16:46',
                'star_nation' => 'manticore',
                'id' => '5828e64ee4bed8314b8b45ae',
            ],
            [
                'display_order' => 1003,
                'name' => 'Solo Aerospace Wings',
                'code' => 'SAW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234348',
            ],
            [
                'display_order' => 1004,
                'name' => 'Enlisted Aerospace Wings',
                'code' => 'EAW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234349',
            ],
            [
                'display_order' => 1005,
                'name' => 'Officer Aerospace Wings',
                'code' => 'OAW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b82123434a',
            ],
            [
                'display_order' => 1006,
                'name' => 'Enlisted Senior Aerospace Wings',
                'code' => 'ESAW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b82123434b',
            ],
            [
                'display_order' => 1007,
                'name' => 'Officer Senior Aerospace Wings',
                'code' => 'OSAW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b82123434c',
            ],
            [
                'display_order' => 1008,
                'name' => 'Enlisted Master Aerospace Wings',
                'code' => 'EMAW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b82123434d',
            ],
            [
                'display_order' => 1009,
                'name' => 'Officer Master Aerospace Wings',
                'code' => 'OMAW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b82123434e',
            ],
            [
                'display_order' => 1010,
                'name' => 'Enlisted Navigator Wings',
                'code' => 'ENW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b82123434f',
            ],
            [
                'display_order' => 1011,
                'name' => 'Officer Navigator Wings',
                'code' => 'ONW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234350',
            ],
            [
                'display_order' => 1012,
                'name' => 'Enlisted Senior Navigator Wings',
                'code' => 'ESNW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234351',
            ],
            [
                'display_order' => 1013,
                'name' => 'Officer Senior Navigator Wings',
                'code' => 'OSNW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234352',
            ],
            [
                'display_order' => 1014,
                'name' => 'Enlisted Master Navigator Wings',
                'code' => 'EMNW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234353',
            ],
            [
                'display_order' => 1015,
                'name' => 'Officer Master Navigator Wings',
                'code' => 'OMNW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234354',
            ],
            [
                'display_order' => 1016,
                'name' => 'Enlisted Observer Wings',
                'code' => 'EOW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234355',
            ],
            [
                'display_order' => 1017,
                'name' => 'Officer Observer Wings',
                'code' => 'OOW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234356',
            ],
            [
                'display_order' => 1018,
                'name' => 'Enlisted Senior Observer Wings',
                'code' => 'ESOW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234357',
            ],
            [
                'display_order' => 1019,
                'name' => 'Officer Senior Observer Wings',
                'code' => 'OSOW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234358',
            ],
            [
                'display_order' => 1020,
                'name' => 'Enlisted Master Observer Wings',
                'code' => 'EMOW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234359',
            ],
            [
                'display_order' => 1021,
                'name' => 'Officer Master Observer Wings',
                'code' => 'OMOW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b82123435a',
            ],
            [
                'display_order' => 1022,
                'name' => 'Enlisted Simulator Wings',
                'code' => 'ESW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,OSW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b82123435b',
            ],
            [
                'display_order' => 1023,
                'name' => 'Officer Simulator Wings',
                'code' => 'OSW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,ESSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b82123435c',
            ],
            [
                'display_order' => 1024,
                'name' => 'Enlisted Senior Simulator Wings',
                'code' => 'ESSW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,OSSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b82123435d',
            ],
            [
                'display_order' => 1025,
                'name' => 'Officer Senior Simulator Wings',
                'code' => 'OSSW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,EMSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b82123435e',
            ],
            [
                'display_order' => 1026,
                'name' => 'Enlisted Master Simulator Wings',
                'code' => 'EMSW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,OMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b82123435f',
            ],
            [
                'display_order' => 1027,
                'name' => 'Officer Master Simulator Wings',
                'code' => 'OMSW',
                'post_nominal' => '',
                'replaces' => 'HS,OSWP,ESWP,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,CIB',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234360',
            ],
            [
                'display_order' => 1028,
                'name' => 'Royal Manticoran Army Combat Infantry Badge',
                'code' => 'CIB',
                'post_nominal' => '',
                'replaces' => 'OSWP,ESWP,HS,SAW,EAW,OAW,ESAW,OSAW,EMAW,OMAW,ENW,ONW,ESNW,OSNW,EMNW,OMNW,EOW,OOW,ESOW,OSOW,EMOW,OMOW,ESW,OSW,ESSW,OSSW,EMSW,OMSW',
                'location' => 'TL',
                'multiple' => false,
                'group_label' => 'Qualification Badges',
                'star_nation' => 'manticore',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:36:14',
                'id' => '5b0c4c1ecbe77603d215d9b7',
            ],
            [
                'display_order' => 2000,
                'name' => 'HMS UNCONQUERED',
                'code' => 'UNC',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'LS',
                'multiple' => false,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2017-07-31 15:38:41',
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234362',
            ],
            [
                'display_order' => 2001,
                'name' => 'Member, Privy Council',
                'code' => 'PC',
                'post_nominal' => 'PC',
                'location' => 'LS',
                'multiple' => false,
                'star_nation' => 'manticore',
                'updated_at' => '2019-08-12 00:30:37',
                'created_at' => '2019-08-12 00:30:37',
                'id' => '5d50b32d9c6b7f11984a4237',
            ],
            [
                'display_order' => 3000,
                'name' => 'Monarch\'s Thanks',
                'code' => 'MT',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'RS',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2017-07-31 15:38:41',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234364',
            ],
            [
                'display_order' => 3001,
                'name' => 'Mentioned in Dispatches',
                'code' => 'MID',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'RS',
                'multiple' => false,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2017-07-31 15:38:41',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234366',
            ],
            [
                'display_order' => 3002,
                'name' => 'Wound Stripe',
                'code' => 'WS',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'RS',
                'multiple' => true,
                'updated_at' => '2018-05-28 18:35:30',
                'created_at' => '2017-07-31 15:38:41',
                'points' => 1,
                'star_nation' => 'manticore',
                'id' => '597f4f014b3df7b821234365',
            ],
            [
                'display_order' => 4000,
                'name' => 'Army Grenade High Expert Rating',
                'code' => 'AGHER',
                'post_nominal' => '',
                'replaces' => 'AGER,AGSR,AGMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Grenade Marksmanship',
                'image' => 'AHER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 4,
                'id' => '5b0c4bf2cbe77603d215d96c',
            ],
            [
                'display_order' => 4001,
                'name' => 'Army Disrupter High Expert Rating',
                'code' => 'ADHER',
                'post_nominal' => '',
                'replaces' => 'ADER,ADSR,ADMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Disrupter Marksmanship',
                'image' => 'AHER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 4,
                'id' => '5b0c4bf2cbe77603d215d96d',
            ],
            [
                'display_order' => 4002,
                'name' => 'Army Flechette Gun High Expert Rating',
                'code' => 'AFGHER',
                'post_nominal' => '',
                'replaces' => 'AFGER,AFGSR,AFGMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Flechette Gun Marksmanship',
                'image' => 'AHER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 4,
                'id' => '5b0c4bf2cbe77603d215d96e',
            ],
            [
                'display_order' => 4003,
                'name' => 'Army Pistol High Expert Rating',
                'code' => 'APHER',
                'post_nominal' => '',
                'replaces' => 'APER,APSR,APMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Pistol Marksmanship',
                'image' => 'AHER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 4,
                'id' => '5b0c4bf2cbe77603d215d96f',
            ],
            [
                'display_order' => 4004,
                'name' => 'Army Rifle High Expert Rating',
                'code' => 'ARHER',
                'post_nominal' => '',
                'replaces' => 'ARER,ARSR,ARMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Rifle Marksmanship',
                'image' => 'AHER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 4,
                'id' => '5b0c4bf2cbe77603d215d970',
            ],
            [
                'display_order' => 4005,
                'name' => 'Army Grenade Launcher High Expert Rating',
                'code' => 'AGLHER',
                'post_nominal' => '',
                'replaces' => 'AGLER,AGLSR,AGLMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Grenade Launcher Marksmanship',
                'image' => 'AHER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 4,
                'id' => '5b0c4bf2cbe77603d215d971',
            ],
            [
                'display_order' => 4006,
                'name' => 'Army Tribarrel High Expert Rating',
                'code' => 'ATHER',
                'post_nominal' => '',
                'replaces' => 'ATER,ATSR,ATMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Tribarrel Marksmanship',
                'image' => 'AHER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 4,
                'id' => '5b0c4bf2cbe77603d215d972',
            ],
            [
                'display_order' => 4007,
                'name' => 'Army Plasma Carbine High Expert Rating',
                'code' => 'APCHER',
                'post_nominal' => '',
                'replaces' => 'APCER,APCSR,APCMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Plasma Carbine Marksmanship',
                'image' => 'AHER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 4,
                'id' => '5b0c4bf2cbe77603d215d973',
            ],
            [
                'display_order' => 4008,
                'name' => 'Army Plasma Rifle High Expert Rating',
                'code' => 'APRHER',
                'post_nominal' => '',
                'replaces' => 'APRER,APRSR,APRMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Plasma Rifle Marksmanship',
                'image' => 'AHER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 4,
                'id' => '5b0c4bf2cbe77603d215d974',
            ],
            [
                'display_order' => 4009,
                'name' => 'Army Grenade Expert Rating',
                'code' => 'AGER',
                'post_nominal' => '',
                'replaces' => 'AGSR,AGMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Grenade Marksmanship',
                'image' => 'AER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 3,
                'id' => '5b0c4bf2cbe77603d215d975',
            ],
            [
                'display_order' => 4010,
                'name' => 'Army Disrupter Expert Rating',
                'code' => 'ADER',
                'post_nominal' => '',
                'replaces' => 'ADSR,ADMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Disrupter Marksmanship',
                'image' => 'AER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 3,
                'id' => '5b0c4bf2cbe77603d215d976',
            ],
            [
                'display_order' => 4011,
                'name' => 'Army Flechette Gun Expert Rating',
                'code' => 'AFGER',
                'post_nominal' => '',
                'replaces' => 'AFGSR,AFGMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Flechette Gun Marksmanship',
                'image' => 'AER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 3,
                'id' => '5b0c4bf2cbe77603d215d977',
            ],
            [
                'display_order' => 4012,
                'name' => 'Army Pistol Expert Rating',
                'code' => 'APER',
                'post_nominal' => '',
                'replaces' => 'APSR,APMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Pistol Marksmanship',
                'image' => 'AER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 3,
                'id' => '5b0c4bf2cbe77603d215d978',
            ],
            [
                'display_order' => 4013,
                'name' => 'Army Rifle Expert Rating',
                'code' => 'ARER',
                'post_nominal' => '',
                'replaces' => 'ARSR,ARMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Rifle Marksmanship',
                'image' => 'AER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 3,
                'id' => '5b0c4bf2cbe77603d215d979',
            ],
            [
                'display_order' => 4014,
                'name' => 'Army Grenade Launcher Expert Rating',
                'code' => 'AGLER',
                'post_nominal' => '',
                'replaces' => 'AGLSR,AGLMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Grenade Launcher Marksmanship',
                'image' => 'AER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 3,
                'id' => '5b0c4bf2cbe77603d215d97a',
            ],
            [
                'display_order' => 4015,
                'name' => 'Army Tribarrel Expert Rating',
                'code' => 'ATER',
                'post_nominal' => '',
                'replaces' => 'ATSR,ATMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Tribarrel Marksmanship',
                'image' => 'AER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 3,
                'id' => '5b0c4bf2cbe77603d215d97b',
            ],
            [
                'display_order' => 4016,
                'name' => 'Army Plasma Carbine Expert Rating',
                'code' => 'APCER',
                'post_nominal' => '',
                'replaces' => 'APCSR,APCMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Plasma Carbine Marksmanship',
                'image' => 'AER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 3,
                'id' => '5b0c4bf2cbe77603d215d97c',
            ],
            [
                'display_order' => 4017,
                'name' => 'Army Plasma Rifle Expert Rating',
                'code' => 'APRER',
                'post_nominal' => '',
                'replaces' => 'APRSR,APRMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Plasma Rifle Marksmanship',
                'image' => 'AER.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 3,
                'id' => '5b0c4bf2cbe77603d215d97d',
            ],
            [
                'display_order' => 4018,
                'name' => 'Army Grenade Sharpshooter Rating',
                'code' => 'AGSR',
                'post_nominal' => '',
                'replaces' => 'AGMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Grenade Marksmanship',
                'image' => 'ASR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 2,
                'id' => '5b0c4bf2cbe77603d215d97e',
            ],
            [
                'display_order' => 4019,
                'name' => 'Army Disrupter Sharpshooter Rating',
                'code' => 'ADSR',
                'post_nominal' => '',
                'replaces' => 'ADMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Disrupter Marksmanship',
                'image' => 'ASR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 2,
                'id' => '5b0c4bf2cbe77603d215d97f',
            ],
            [
                'display_order' => 4020,
                'name' => 'Army Flechette Gun Sharpshooter Rating',
                'code' => 'AFGSR',
                'post_nominal' => '',
                'replaces' => 'AFGMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Flechette Gun Marksmanship',
                'image' => 'ASR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 2,
                'id' => '5b0c4bf2cbe77603d215d980',
            ],
            [
                'display_order' => 4021,
                'name' => 'Army Pistol Sharpshooter Rating',
                'code' => 'APSR',
                'post_nominal' => '',
                'replaces' => 'APMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Pistol Marksmanship',
                'image' => 'ASR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 2,
                'id' => '5b0c4bf2cbe77603d215d981',
            ],
            [
                'display_order' => 4022,
                'name' => 'Army Rifle Sharpshooter Rating',
                'code' => 'ARSR',
                'post_nominal' => '',
                'replaces' => 'ARMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Rifle Marksmanship',
                'image' => 'ASR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 2,
                'id' => '5b0c4bf2cbe77603d215d982',
            ],
            [
                'display_order' => 4023,
                'name' => 'Army Grenade Launcher Sharpshooter Rating',
                'code' => 'AGLSR',
                'post_nominal' => '',
                'replaces' => 'AGLMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Grenade Launcher Marksmanship',
                'image' => 'ASR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 2,
                'id' => '5b0c4bf2cbe77603d215d983',
            ],
            [
                'display_order' => 4024,
                'name' => 'Army Tribarrel Sharpshooter Rating',
                'code' => 'ATSR',
                'post_nominal' => '',
                'replaces' => 'ATMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Tribarrel Marksmanship',
                'image' => 'ASR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 2,
                'id' => '5b0c4bf2cbe77603d215d984',
            ],
            [
                'display_order' => 4025,
                'name' => 'Army Plasma Carbine Sharpshooter Rating',
                'code' => 'APCSR',
                'post_nominal' => '',
                'replaces' => 'APCMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Plasma Carbine Marksmanship',
                'image' => 'ASR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 2,
                'id' => '5b0c4bf2cbe77603d215d985',
            ],
            [
                'display_order' => 4026,
                'name' => 'Army Plasma Rifle Sharpshooter Rating',
                'code' => 'APRSR',
                'post_nominal' => '',
                'replaces' => 'APRMR',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Plasma Rifle Marksmanship',
                'image' => 'ASR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 2,
                'id' => '5b0c4bf2cbe77603d215d986',
            ],
            [
                'display_order' => 4027,
                'name' => 'Army Grenade Marksmanship Rating',
                'code' => 'AGMR',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Grenade Marksmanship',
                'image' => 'AMR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 1,
                'id' => '5b0c4bf2cbe77603d215d987',
            ],
            [
                'display_order' => 4028,
                'name' => 'Army Disrupter Marksmanship Rating',
                'code' => 'ADMR',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Disrupter Marksmanship',
                'image' => 'AMR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 1,
                'id' => '5b0c4bf2cbe77603d215d988',
            ],
            [
                'display_order' => 4029,
                'name' => 'Army Flechette Gun Marksmanship Rating',
                'code' => 'AFGMR',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Flechette Gun Marksmanship',
                'image' => 'AMR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 1,
                'id' => '5b0c4bf2cbe77603d215d989',
            ],
            [
                'display_order' => 4030,
                'name' => 'Army Pistol Marksmanship Rating',
                'code' => 'APMR',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Pistol Marksmanship',
                'image' => 'AMR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 1,
                'id' => '5b0c4bf2cbe77603d215d98a',
            ],
            [
                'display_order' => 4031,
                'name' => 'Army Rifle Marksmanship Rating',
                'code' => 'ARMR',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Rifle Marksmanship',
                'image' => 'AMR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 1,
                'id' => '5b0c4bf2cbe77603d215d98b',
            ],
            [
                'display_order' => 4032,
                'name' => 'Army Grenade Launcher Marksmanship Rating',
                'code' => 'AGLMR',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Grenade Launcher Marksmanship',
                'image' => 'AMR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 1,
                'id' => '5b0c4bf2cbe77603d215d98c',
            ],
            [
                'display_order' => 4033,
                'name' => 'Army Tribarrel Marksmanship Rating',
                'code' => 'ATMR',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Tribarrel Marksmanship',
                'image' => 'AMR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 1,
                'id' => '5b0c4bf2cbe77603d215d98d',
            ],
            [
                'display_order' => 4034,
                'name' => 'Army Plasma Carbine Marksmanship Rating',
                'code' => 'APCMR',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Plasma Carbine Marksmanship',
                'image' => 'AMR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 1,
                'id' => '5b0c4bf2cbe77603d215d98e',
            ],
            [
                'display_order' => 4035,
                'name' => 'Army Plasma Rifle Marksmanship Rating',
                'code' => 'APRMR',
                'post_nominal' => '',
                'replaces' => '',
                'location' => 'AWQ',
                'multiple' => false,
                'group_label' => 'Army Plasma Rifle Marksmanship',
                'image' => 'AMR.png',
                'updated_at' => '2018-05-28 18:36:14',
                'created_at' => '2018-05-28 18:35:30',
                'star_nation' => 'manticore',
                'points' => 1,
                'id' => '5b0c4bf2cbe77603d215d98f',
            ],
        ];

        foreach ($awards as $award) {
            $rec = new Award($award);
            $rec->created_at = $award['created_at'];
            $rec->updated_at = $award['updated_at'];
            $rec->timestamps = false;
            $rec->save();
        }
    }
}
